#ifndef CONFIG_H
#define CONFIG_H

/* Important Kernel definitions */
#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10
#define LIBREWIN_TOTAL_INTERRUPTS 512

/* 100MB heap size */
#define LIBREWIN_HEAP_SIZE_BYTES 104857600
#define LIBREWIN_HEAP_BLOCK_SIZE 4096
#define LIBREWIN_HEAP_ADDRESS 0x01000000
#define LIBREWIN_HEAP_TABLE_ADDRESS 0x00007E00

#define LIBREWIN_SECTOR_SIZE 512

#define LIBREWIN_MAX_PATH 108

#define LIBREWIN_MAX_FILESYSTEMS 12
#define LIBREWIN_MAX_FILE_DESCRIPTORS 512

#define LIBREWIN_TOTAL_GDT_SEGMENTS 6

#define LIBREWIN_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define LIBREWIN_USER_PROGRAM_STACK_SIZE 1024 * 16
#define LIBREWIN_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define LIBREWIN_PROGRAM_VIRTUAL_STACK_ADDRESS_END LIBREWIN_PROGRAM_VIRTUAL_ADDRESS_START - LIBREWIN_USER_PROGRAM_STACK_SIZE

#define LIBREWIN_MAX_PROGRAM_ALLOCATIONS 1024
#define LIBREWIN_MAX_PROCESSES 12

#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1b

#endif
